import { Category, Product } from '../types/database.types';

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('tr-TR', {
    style: 'currency',
    currency: 'TRY',
    maximumFractionDigits: 2,
  }).format(amount);
}

export function cn(...classes: (string | undefined | null | false)[]): string {
  return classes.filter(Boolean).join(' ');
}

export const SAMPLE_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Motor ve Aktarma Organları',
    slug: 'motor-aktarma',
    description: 'Triger setleri, filtreler, bujiler, yağ devirdaim ve motor performans parçaları.',
    image_url: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=800&q=80',
    icon_name: 'Cpu',
    item_count: 1240,
  },
  {
    id: 'cat-2',
    name: 'Fren ve Süspansiyon',
    slug: 'fren-suspansiyon',
    description: 'Fren diskleri, balatalar, amortisörler, salıncak ve direksiyon kutuları.',
    image_url: 'https://images.unsplash.com/photo-1600793575654-910699b5e4d4?auto=format&fit=crop&w=800&q=80',
    icon_name: 'Disc',
    item_count: 850,
  },
  {
    id: 'cat-3',
    name: 'Aydınlatma ve Elektrik',
    slug: 'aydinlatma-elektrik',
    description: 'LED Farlar, stop lambaları, aküler, sensörler ve şarj sistemleri.',
    image_url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80',
    icon_name: 'Zap',
    item_count: 620,
  },
  {
    id: 'cat-4',
    name: 'Kaporta ve Dış Aksesuar',
    slug: 'kaporta-aksesuar',
    description: 'Tamponlar, ızgaralar, aynalar, rüzgarlıklar ve koruma barları.',
    image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    icon_name: 'ShieldCheck',
    item_count: 490,
  },
  {
    id: 'cat-5',
    name: 'İç Donanım ve Bakım',
    slug: 'ic-donanim-bakim',
    description: 'Koltuk kılıfları, paspaslar, araç içi multimedya ve oto bakım kimyasalları.',
    image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    icon_name: 'Sparkles',
    item_count: 930,
  },
];

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Brembo Performans Ön Fren Disk & Balata Seti',
    slug: 'brembo-on-fren-disk-balata-seti',
    category: 'Fren ve Süspansiyon',
    category_slug: 'fren-suspansiyon',
    brand: 'Brembo',
    part_number: 'BRM-98742-FR',
    vehicle_compatibility: [
      { brand: 'Volkswagen', model: 'Golf VII / Passat B8', years: '2013-2021' },
      { brand: 'Audi', model: 'A3 8V', years: '2014-2020' },
      { brand: 'Seat', model: 'Leon 5F', years: '2013-2020' },
    ],
    price: 4850,
    discount_price: 4290,
    stock: 24,
    image_url: 'https://images.unsplash.com/photo-1600793575654-910699b5e4d4?auto=format&fit=crop&w=800&q=80',
    description: 'Yüksek ısıya dayanıklı özel alaşım seramik kaplamalı Brembo ön fren diskleri ve sessiz balata kiti. Maksimum tutuş ve kısa duruş mesafesi sağlar.',
    specs: {
      'Çap': '312 mm',
      'Balata Tipi': 'Seramik Katkılı Low-Metallic',
      'Garanti': '2 Yıl',
      'Menşei': 'İtalya',
    },
    rating: 4.9,
    reviews_count: 38,
    is_featured: true,
  },
  {
    id: 'prod-2',
    title: 'Bosch Triger Kayış Seti + Devirdaim Pompası Kit',
    slug: 'bosch-triger-kayis-seti-devirdaim-pompasi',
    category: 'Motor ve Aktarma Organları',
    category_slug: 'motor-aktarma',
    brand: 'Bosch',
    part_number: 'BSH-TRG-1.6TDI',
    vehicle_compatibility: [
      { brand: 'Volkswagen', model: '1.6 TDI / 2.0 TDI Motorlar', years: '2010-2022' },
      { brand: 'Skoda', model: 'Octavia / Superb', years: '2012-2022' },
    ],
    price: 3950,
    discount_price: 3450,
    stock: 15,
    image_url: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=800&q=80',
    description: 'Orijinal ekipman kalitesinde Bosch triger kayış seti, gergi bilyaları ve su pompası kombinasyonu. Ağır bakım periyodunuz için eksiksiz paket.',
    specs: {
      'Kayış Diş Sayısı': '145',
      'Gövde': 'Kevlar Takviyeli',
      'Su Pompası Contası': 'Dahil',
      'Garanti': '2 Yıl / 80.000 KM',
    },
    rating: 4.8,
    reviews_count: 52,
    is_featured: true,
  },
  {
    id: 'prod-3',
    title: 'Osram Night Breaker Laser H7 LED Far Ampul Seti',
    slug: 'osram-night-breaker-laser-h7-led-far-ampul',
    category: 'Aydınlatma ve Elektrik',
    category_slug: 'aydinlatma-elektrik',
    brand: 'Osram',
    part_number: 'OSR-H7-NBL-LED',
    vehicle_compatibility: [
      { brand: 'Evrensel Uyum', model: 'H7 Far Yuvası Olan Tüm Araçlar', years: '2000-2026' },
    ],
    price: 2450,
    discount_price: 1990,
    stock: 40,
    image_url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80',
    description: '%200 daha fazla parlaklık ve 150m daha uzun görüş mesafesi sağlayan Alman teknolojisi Osram kristal beyaz LED far seti.',
    specs: {
      'Işık Rengi': '6000K Soğuk Beyaz',
      'Güç': '55W / Ampul',
      'Canbus Desteği': 'Var (Arıza Işığı Yakmaz)',
      'Soğutma': 'Fanlı Alüminyum Gövde',
    },
    rating: 4.7,
    reviews_count: 89,
    is_featured: true,
  },
  {
    id: 'prod-4',
    title: 'Sachs Gazlı Arka Amortisör Takımı (Çift)',
    slug: 'sachs-gazli-arka-amortisor-takimi-cift',
    category: 'Fren ve Süspansiyon',
    category_slug: 'fren-suspansiyon',
    brand: 'Sachs',
    part_number: 'SCH-314-718',
    vehicle_compatibility: [
      { brand: 'BMW', model: '3 Serisi F30 / F31', years: '2012-2019' },
      { brand: 'BMW', model: '4 Serisi F32', years: '2013-2020' },
    ],
    price: 5200,
    discount_price: 4650,
    stock: 8,
    image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    description: 'Sürüş konforunu ve viraj kararlılığını ilk günkü seviyesine çıkartan orijinal üretici Sachs gazlı amortisör takımı.',
    specs: {
      'Tip': 'Çift Tüplü Gaz Basınçlı',
      'Montaj Yönü': 'Arka Sağ / Sol',
      'Uyum': 'M-Sport ve Standart Süspansiyon Uyumlu',
    },
    rating: 5.0,
    reviews_count: 14,
    is_featured: false,
  },
  {
    id: 'prod-5',
    title: 'Liqui Moly Top Tec 4200 5W-30 Motor Yağı (5 Litre)',
    slug: 'liqui-moly-top-tec-4200-5w30-motor-yagi-5l',
    category: 'İç Donanım ve Bakım',
    category_slug: 'ic-donanim-bakim',
    brand: 'Liqui Moly',
    part_number: 'LQ-3707-5L',
    vehicle_compatibility: [
      { brand: 'Evrensel Uyum', model: 'Benzinli & DPFli Dizel Motorlar', years: '2005-2026' },
    ],
    price: 2150,
    discount_price: 1850,
    stock: 50,
    image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    description: 'Almanya üretimi sentetik motor yağı. Tortu oluşumunu engeller, sürtünmeyi minimize ederek yakıt tasarrufu ve maksimum motor koruması sunar.',
    specs: {
      'Viskozite': '5W-30',
      'Hacim': '5 Litre',
      'Onaylar': 'VW 504 00 / 507 00, MB 229.51, BMW Longlife-04',
    },
    rating: 4.9,
    reviews_count: 120,
    is_featured: true,
  },
];
