import { Category, Product } from '../types/database.types';

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('tr-TR', {
    style: 'currency',
    currency: 'TRY',
    maximumFractionDigits: 2,
  }).format(amount);
}

export function cn(...classes: (string | undefined | null | false)[]): string {
  return classes.filter(Boolean).join(' ');
}

export const SAMPLE_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Motor ve Aktarma Organları',
    slug: 'motor-aktarma',
    description: 'Triger setleri, filtreler, bujiler, yağ devirdaim ve motor performans parçaları.',
    image_url: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=800&q=80',
    icon_name: 'Cpu',
    item_count: 1240,
  },
  {
    id: 'cat-2',
    name: 'Fren ve Süspansiyon',
    slug: 'fren-suspansiyon',
    description: 'Fren diskleri, balatalar, amortisörler, salıncak ve direksiyon kutuları.',
    image_url: 'https://images.unsplash.com/photo-1600793575654-910699b5e4d4?auto=format&fit=crop&w=800&q=80',
    icon_name: 'Disc',
    item_count: 850,
  },
  {
    id: 'cat-3',
    name: 'Aydınlatma ve Elektrik',
    slug: 'aydinlatma-elektrik',
    description: 'LED Farlar, stop lambaları, sensörler, bobinler ve bujiler.',
    image_url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80',
    icon_name: 'Zap',
    item_count: 620,
  },
  {
    id: 'cat-4',
    name: 'Kaporta ve Dış Aksesuar',
    slug: 'kaporta-aksesuar',
    description: 'Tamponlar, ızgaralar, aynalar, rüzgarlıklar ve koruma barları.',
    image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    icon_name: 'ShieldCheck',
    item_count: 490,
  },
  {
    id: 'cat-5',
    name: 'İç Donanım ve Periyodik Bakım',
    slug: 'ic-donanim-bakim',
    description: 'Orijinal PSA/GM motor yağları, filtre kitleri ve oto bakım kimyasalları.',
    image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    icon_name: 'Sparkles',
    item_count: 930,
  },
];

export const SAMPLE_PRODUCTS: Product[] = [
  // 1. OPEL
  {
    id: 'prod-opel-1',
    title: 'Opel Astra J / Insignia A 1.6 CDTI Orijinal Triger Zincir Seti',
    slug: 'opel-astra-j-insignia-1-6-cdti-orijinal-triger-zincir-seti',
    category: 'Motor ve Aktarma Organları',
    category_slug: 'motor-aktarma',
    brand: 'GM / Opel Orijinal',
    part_number: 'GM-55588383-TRG',
    oem_reference_number: '55588383 / 636136',
    is_original: true,
    part_quality: 'original',
    vehicle_compatibility: [
      { brand: 'Opel', model: 'Astra J 1.6 CDTI (B16DTL / B16DTH)', years: '2013-2020' },
      { brand: 'Opel', model: 'Insignia A 1.6 CDTI', years: '2015-2017' },
      { brand: 'Opel', model: 'Mokka 1.6 CDTI', years: '2015-2020' },
    ],
    price: 6850,
    discount_price: 6190,
    stock: 12,
    image_url: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=800&q=80',
    description: 'Opel B16DTH motor kodlu 1.6 CDTI araçlar için ses yapmayan güncel revize GM orijinal eksantrik triger zincir kiti, gergi paletleri ve contaları.',
    technical_description: 'Güçlendirilmiş çift bakla çelik zincir, hidrolik gergi mekanizması ve yağ püskürtme memesi dahil tam takım. GM fabrika montaj parçasıdır.',
    specs: {
      'Motor Kodları': 'B16DTL, B16DTH, D16DTH',
      'Paket İçeriği': 'Zincir + 3 Adet Palet + Hidrolik Gergi + Dişliler',
      'Garanti': '2 Yıl / 100.000 KM',
      'Menşei': 'Almanya (GM Hologramlı Kutu)',
    },
    rating: 4.9,
    reviews_count: 46,
    is_featured: true,
    weight_kg: 3.4,
  },
  // 2. PEUGEOT
  {
    id: 'prod-peugeot-1',
    title: 'Peugeot 3008 / 5008 / 2008 1.5 BlueHDi Euro 6.3 Orijinal Eksantrik Zincir Revizyon Kiti (8mm)',
    slug: 'peugeot-3008-1-5-bluehdi-orijinal-eksantrik-zincir-kiti',
    category: 'Motor ve Aktarma Organları',
    category_slug: 'motor-aktarma',
    brand: 'Peugeot Orijinal (PSA)',
    part_number: 'PSA-1638159880',
    oem_reference_number: '1638159880 / 9830147280',
    is_original: true,
    part_quality: 'original',
    vehicle_compatibility: [
      { brand: 'Peugeot', model: '3008 II 1.5 BlueHDi (DV5RC)', years: '2018-2024' },
      { brand: 'Peugeot', model: '2008 II 1.5 BlueHDi', years: '2019-2024' },
      { brand: 'Peugeot', model: '5008 II 1.5 BlueHDi', years: '2018-2024' },
      { brand: 'Peugeot', model: 'Rifter 1.5 BlueHDi', years: '2018-2024' },
    ],
    price: 7450,
    discount_price: 6890,
    stock: 9,
    image_url: 'https://images.unsplash.com/photo-1600793575654-910699b5e4d4?auto=format&fit=crop&w=800&q=80',
    description: 'DV5 1.5 BlueHDi motorlar için PSA fabrikası tarafından güncellenen 8mm takviyeli eksantrik zincir, karter kapağı ve gergi kiti.',
    technical_description: 'Eski 7mm zincir ses ve kopma problemlerine karşı PSA tarafından geliştirilen 8mm revizyonlu OEM takımdır. Subap iticileri ve külbütör contası ile eksiksiz takımdır.',
    specs: {
      'Zincir Kalınlığı': '8 mm (Yeni Tip Güçlendirilmiş)',
      'Motor Kodu': 'DV5RD, DV5RC (1.5 BlueHDi 100/130 HP)',
      'Menşei': 'Fransa (PSA Orijinal)',
      'Garanti': '2 Yıl / 80.000 KM',
    },
    rating: 5.0,
    reviews_count: 62,
    is_featured: true,
    weight_kg: 2.8,
  },
  // 3. CITROËN
  {
    id: 'prod-citroen-1',
    title: 'Citroën C5 Aircross / C4 / Berlingo Ön Fren Disk & Balata Takımı',
    slug: 'citroen-c5-aircross-c4-on-fren-disk-balata-takimi',
    category: 'Fren ve Süspansiyon',
    category_slug: 'fren-suspansiyon',
    brand: 'Brembo',
    part_number: 'BRM-09.C422.13',
    oem_reference_number: '1611839280',
    is_original: true,
    part_quality: 'original',
    vehicle_compatibility: [
      { brand: 'Citroën', model: 'C5 Aircross', years: '2018-2024' },
      { brand: 'Citroën', model: 'C4 III / C4 Cactus', years: '2018-2024' },
      { brand: 'Citroën', model: 'Berlingo III 1.5 BlueHDi / 1.2 PureTech', years: '2018-2024' },
    ],
    price: 4950,
    discount_price: 4350,
    stock: 18,
    image_url: 'https://images.unsplash.com/photo-1600793575654-910699b5e4d4?auto=format&fit=crop&w=800&q=80',
    description: 'Yüksek karbon alaşımlı, paslanmaya karşı UV boyalı Brembo ön fren diskleri ve düşük toz oranlı fren balata seti.',
    technical_description: '304 mm hava kanallı disk geometrisi. Titreşimsiz ve sessiz frenleme için seramik katkılı sürtünme balatası. ECE-R90 fren güvenlik sertifikalı.',
    specs: {
      'Çap': '304 mm',
      'Disk Kalınlığı': '28 mm',
      'Bijon Sayısı': '5',
      'Garanti': '2 Yıl / 60.000 KM',
    },
    rating: 4.8,
    reviews_count: 29,
    is_featured: true,
    weight_kg: 16.2,
  },
  // 4. CHEVROLET
  {
    id: 'prod-chevrolet-1',
    title: 'Chevrolet Cruze / Aveo 1.6 & 1.4 Turbo Komple Alüminyum Termostat Gövdesi',
    slug: 'chevrolet-cruze-aveo-aluminyum-termostat-govdesi',
    category: 'Motor ve Aktarma Organları',
    category_slug: 'motor-aktarma',
    brand: 'Mahle / Behr',
    part_number: 'MHL-TM-36105',
    oem_reference_number: '55577072 / 25192228',
    is_original: true,
    part_quality: 'original',
    vehicle_compatibility: [
      { brand: 'Chevrolet', model: 'Cruze 1.6 / 1.4 Turbo (A16XER / A14NET)', years: '2009-2016' },
      { brand: 'Chevrolet', model: 'Aveo T300 1.4 / 1.6', years: '2011-2018' },
      { brand: 'Chevrolet', model: 'Trax 1.4 Turbo', years: '2013-2019' },
      { brand: 'Opel', model: 'Astra J 1.4 Turbo / 1.6', years: '2010-2018' },
    ],
    price: 2150,
    discount_price: 1850,
    stock: 26,
    image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    description: 'Kronik plastik gövde çatlama ve su kaçaklarını önleyen, dayanıklı döküm alüminyum gövdeli komple termostat ve müşür kiti.',
    technical_description: '105°C açma sıcaklığında entegre ısıtmalı termostat valfi ve sıcaklık sensörü dahil. Döküm alüminyum alaşım sayesinde yüksek hararet dayanımı.',
    specs: {
      'Gövde Malzemesi': 'Döküm Alüminyum (Çatlamaz)',
      'Açılma Sıcaklığı': '105 °C',
      'Sensör': 'Entegre 2 Pinli Isı Müşürü Dahil',
      'Garanti': '2 Yıl',
    },
    rating: 4.9,
    reviews_count: 88,
    is_featured: true,
    weight_kg: 1.1,
  },
  // 5. DS AUTOMOBILES
  {
    id: 'prod-ds-1',
    title: 'DS Automobiles DS 7 Crossback / DS 4 / DS 9 4\'lü Orijinal Periyodik Bakım Filtre Seti',
    slug: 'ds-7-crossback-ds-4-orijinal-periyodik-bakim-filtre-seti',
    category: 'İç Donanım ve Periyodik Bakım',
    category_slug: 'ic-donanim-bakim',
    brand: 'PSA / DS Orijinal',
    part_number: 'DS-FLT-KIT-1.5HDI',
    oem_reference_number: '9804163480 / 9811121880',
    is_original: true,
    part_quality: 'original',
    vehicle_compatibility: [
      { brand: 'DS Automobiles', model: 'DS 7 Crossback 1.5 BlueHDi / 1.6 PureTech', years: '2018-2024' },
      { brand: 'DS Automobiles', model: 'DS 4 II', years: '2021-2024' },
      { brand: 'DS Automobiles', model: 'DS 3 Crossback', years: '2019-2024' },
    ],
    price: 3200,
    discount_price: 2790,
    stock: 14,
    image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    description: 'DS premium araçlar için hava, yağ, mazot ve alerjen tutucu aktif karbonlu polen filtresinden oluşan eksiksiz orijinal bakım seti.',
    technical_description: 'DS Automobiles fabrika montaj onaylı mikro-elyaf filtreleme. Kabin içine giren egzoz gazı ve ince partikülleri %99.5 oranında süzer.',
    specs: {
      'Set İçeriği': 'Yağ + Hava + Karbonlu Alerjen Polen + Yakıt Filtresi',
      'Kalite': '%100 Orijinal DS / PSA Kutulu',
      'Bakım Aralığı': '15.000 KM / 1 Yıl',
      'Garanti': '1 Yıl',
    },
    rating: 5.0,
    reviews_count: 21,
    is_featured: true,
    weight_kg: 1.6,
  },
  // 6. AFTERMARKET MUADIL (OPEL / PEUGEOT / CITROEN)
  {
    id: 'prod-aftermarket-1',
    title: 'Filtron 4\'lü Periyodik Filtre Seti (Opel Astra K / Peugeot 308 / Citroën C3 A Kalite Muadil)',
    slug: 'filtron-4lu-periyodik-filtre-seti-opel-peugeot-citroen',
    category: 'İç Donanım ve Periyodik Bakım',
    category_slug: 'ic-donanim-bakim',
    brand: 'Filtron',
    part_number: 'FLT-PSA-OPL-4SET',
    is_original: false,
    part_quality: 'aftermarket',
    vehicle_compatibility: [
      { brand: 'Opel', model: 'Astra K 1.6 CDTI / 1.2 Turbo', years: '2015-2021' },
      { brand: 'Peugeot', model: '308 II / 208 II 1.5 BlueHDi', years: '2017-2023' },
      { brand: 'Citroën', model: 'C3 III / C-Elysée 1.5 BlueHDi', years: '2018-2023' },
    ],
    price: 1450,
    discount_price: 1190,
    stock: 45,
    image_url: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=800&q=80',
    description: 'Mann-Filter grubu bünyesindeki Filtron marka A kalite ekonomik yan sanayi 4 parça periyodik filtre bakım paketi.',
    technical_description: 'OEM toleranslarında yüksek toz tutma kapasitesi. Karbonlu kabin filtresi ile temiz hava dolaşımı.',
    specs: {
      'Paket': 'Yağ + Hava + Polen + Yakıt Filtresi',
      'Kalite Sınıfı': 'A Kalite Muadil / Yan Sanayi',
      'Üretici': 'Filtron (Mann+Hummel)',
      'Garanti': '1 Yıl / 15.000 KM',
    },
    rating: 4.8,
    reviews_count: 53,
    is_featured: false,
    weight_kg: 1.5,
  },
];
